# Generated by Django 2.0.7 on 2018-08-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20180730_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured?'),
        ),
    ]
