# Generated by Django 2.0.7 on 2018-07-30 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='nombre rol')),
            ],
        ),
        migrations.CreateModel(
            name='MovieStill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='nombre')),
                ('image', models.FileField(blank=True, null=True, upload_to='movies/stills/', verbose_name='imagen')),
                ('order', models.IntegerField(verbose_name='orden')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='pais'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='director'),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_link',
            field=models.URLField(blank=True, max_length=128, null=True, verbose_name='link IMDB'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.FileField(blank=True, null=True, upload_to='movies/posters/', verbose_name='poster'),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_link',
            field=models.URLField(blank=True, max_length=128, null=True, verbose_name='link trailer'),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='año'),
        ),
        migrations.AddField(
            model_name='moviestill',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='movie',
            name='role',
            field=models.ManyToManyField(to='movies.MovieRole'),
        ),
    ]
