# Generated by Django 2.0.7 on 2018-08-02 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20180730_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=128, null=True, verbose_name='Texto Quote')),
                ('author', models.CharField(blank=True, max_length=64, null=True, verbose_name='Autor Quote')),
            ],
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-year']},
        ),
        migrations.AddField(
            model_name='movie',
            name='synopsis',
            field=models.TextField(blank=True, null=True, verbose_name='sinopsis'),
        ),
        migrations.AddField(
            model_name='moviequote',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
        ),
    ]
